### ISSUE TITLE
Times out when creating screenshots

### ISSUE THREAD

**Issue by d8vjork** [stefanzweifel/sidecar-browsershot#130] opened 2024-05-14 10:49 UTC
<img width="1296" alt="image" src="https://github.com/stefanzweifel/sidecar-browsershot/assets/2331052/de1b3c7e-adfd-478b-b273-682e6fcfd264">

I just upgraded everything to be on the latest (also using node20) because it was failing on the node18 (using the previous version of this function)

Already tried with several things but no luck, this is the code:

```php
$base64Screenshot = Browsershot::url($temporarySignedUrl)
            ->select('#graphContainer')
            ->windowSize((int) round((int) $this->data->width), (int) round((int) $this->data->height))
            ->waitForSelector('#graphContainer')
            ->setExtraHttpHeaders([
                'ngrok-skip-browser-warning' => '69420',
            ])
            ->waitUntilNetworkIdle(false)
            ->noSandbox()
            ->base64Screenshot();
```

**Comment by stefanzweifel** [comment] 2024-05-14 15:07
Thanks for reporting. I currently can't reproduce this issue. :/
Just to confirm, you've upgrade the Lambda function to use Node 20 and updated sidecar-browsershot to the latest version, right?

I see "protocolTimeout" in the error message. Not the first time I heard about this. It came up in #100, but should have been resolved in the latest versions of the packages.

---

Telling you to increase the timeout doesn't help either. It's already quite high.

**Comment by stefanzweifel** [comment] 2024-07-06 13:25
Closing this issue as I'm unable to reproduce this error.

**Closed by stefanzweifel** 2024-07-06 13:25 UTC
